### ISSUE TITLE
prophet_plot_components(m, forecast) Error in rowSums(df[, holiday.comps]) : 'x' must be an array of at least two dimensions

### ISSUE THREAD

**Issue by azmorley** [facebookincubator/prophet#34] opened 2017-02-27 15:26 UTC
Hi,

Everything seems to work fine when I forecast my data without holidays, and mostly works fine when I add in holidays, except for `prophet_plot_components(m, forecast)` which gives me the error

`Error in rowSums(df[, holiday.comps]) : 'x' must be an array of at least two dimensions`

I can plot/view the forecast, but just not the plot components. When I try to view `df[, holiday.comps]` I get the error

`Error in [.data.frame(df, , holiday.comps) : undefined columns selected`

Any thoughts would be much appreciated!

Thanks

**Comment by xhesc** [comment] 2017-02-27 19:14
Duplicate of #31

**Comment by bletham** [comment] 2017-02-28 08:57
@azmorley if you install the Github version to get the fix in #39 does it work for you?

**Comment by azmorley** [comment] 2017-02-28 10:18
Doesn't seem to work for me, I'm getting the same issue still.

**Comment by bletham** [comment] 2017-02-28 13:08
Can you paste your holidays dataframe so I can try to replicate? Also, what is the shape of `forecast`?

**Comment by azmorley** [comment] 2017-02-28 16:29
The holidays I'm using are our company's Black Friday sales period. We're trying to forecast total number of orders, with weekly data going back to 2009. Our data has a couple of key sales periods but as Black Friday is by far the biggest spike, this is the only 'holiday' we have included at present.

```
BlackFridays <- data_frame(
  holiday = 'BlackFriday',
  ds = as.Date(c('2007-11-26', '2008-12-01', '2009-11-30', '2010-11-29', '2011-11-28', '2012-12-10'
                  ,'2013-12-02', '2014-11-28', '2015-11-27', '2016-11-25', '2017-11-24')),
  lower_window = 3,
  upper_window = 3
)
```

The forecast looks good, with a large spike around Black Friday and even a spike around the time of our main Summer sale. it fits the historical trend fairly well (though still can't quite fit the extreme number of orders we get around Black Friday).

```
> tail(forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper', 'BlackFriday')])

            ds     yhat yhat_lower yhat_upper BlackFriday
430 2017-11-20 39153.40   35329.04   42721.88       0.000
431 2017-11-27 39560.27   35800.32   43521.27   -3518.919
432 2017-12-04 44010.21   39923.43   47756.38       0.000
433 2017-12-11 41848.96   37978.81   45582.00       0.000
434 2017-12-18 37880.10   34284.02   41330.70       0.000
435 2017-12-25 33780.24   29921.00   37436.34       0.000
```

**Comment by bletham** [comment] 2017-03-01 08:26
I was able to replicate this error in the CRAN version, but it is working for me with the Github version. Could you try re-installing from Github one more time to see if the problem persists?
`devtools::install_github('facebookincubator/prophet', subdir='R')`

**Comment by azmorley** [comment] 2017-03-01 10:20
Ah yeah it works now, I must have messed up the install somehow!

Thanks :)

**Closed** 2017-03-01 10:24 UTC
